### ISSUE TITLE
PullRequest Comment Task don't set proper status

### ISSUE THREAD

**Issue by knoxi** [joachimdalen/azdevops-pull-request-utils#13]
Since July, the task `PullRequestComments` creates a new PR comment with an invalid status `Unknown` in Azure DevOps.

![image](https://user-images.githubusercontent.com/5229316/185078260-c503ecdf-d19a-4233-aef5-5b31264f3721.png)

With this invalid status, it's not possible to block a PR.

Task:
```
  - task: PullRequestComments@0
    displayName: 'Post a pull request comment reminder for checking the documentation'
    inputs:
      action: 'createOrUpdate'
      content: 'Please check if the changes on this PR needs some documentation update.'
      status: 'Active'
      commentId: 'pr-comment-documentation'
      useDefined: true
      pullRequestId: '${{ parameters.pullRequestId }}'
      type: 'System'
```

Task Log:
```
Starting: Post a pull request comment reminder for checking the documentation
==============================================================================
Task         : Pull Request Comments
Description  : Add comments to a pull request
Version      : 0.4.0
Author       : Joachim Dalen
Help         : https://docs.devops-extensions.dev/docs/extensions/pull-request-utils/tasks/pull-request-comments
==============================================================================
Finishing: Post a pull request comment reminder for checking the documentation
```
