### ISSUE TITLE
Task is missing on Azure DevOps pipelines

### ISSUE THREAD

**Issue by nicholas-chien** [joachimdalen/azdevops-pull-request-utils#9]
Azure DevOps pipeline shows error messages below while validating yml:
![image](https://user-images.githubusercontent.com/103807048/163772569-9264b087-28e0-473c-8c18-286bcebd2bc4.png)

Here is the yml content which relates to Pull Request Utils:
```
      - task: PullRequestDescription@0
        name: RetrievePullRequestDescription
        inputs:
          action: 'view'
          outputVariable: 'PullRequest.DescriptionContent'
          isOutput: true
          stripIdentifiers: false
```

Extension has confirmed to be installed and has needed permission for build service
![image](https://user-images.githubusercontent.com/103807048/163772870-45646bfd-81bb-443c-8e57-6cf49656bce3.png)

![image](https://user-images.githubusercontent.com/103807048/163773005-08353a6b-eb1b-439a-880c-0e295d91d27c.png)

Is there any possible that I miss something?
